const countries = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Albanie', code: 'AL' },
  { name: 'Algérie', code: 'DZ' },
  { name: 'Andorre', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Antigua-et-Barbuda', code: 'AG' },
  { name: 'Argentine', code: 'AR' },
  { name: 'Arménie', code: 'AM' },
  { name: 'Australie', code: 'AU' },
  { name: 'Autriche', code: 'AT' },
  { name: 'Azerbaïdjan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahreïn', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbade', code: 'BB' },
  { name: 'Biélorussie', code: 'BY' },
  { name: 'Belgique', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Bénin', code: 'BJ' },
  { name: 'Bhoutan', code: 'BT' },
  { name: 'Bolivie', code: 'BO' },
  { name: 'Bosnie-Herzégovine', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Brésil', code: 'BR' },
  { name: 'Brunei', code: 'BN' },
  { name: 'Bulgarie', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cabo Verde', code: 'CV' },
  { name: 'Cambodge', code: 'KH' },
  { name: 'Cameroun', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'République centrafricaine', code: 'CF' },
  { name: 'Tchad', code: 'TD' },
  { name: 'Chili', code: 'CL' },
  { name: 'Chine', code: 'CN' },
  { name: 'Colombie', code: 'CO' },
  { name: 'Comores', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Côte d'Ivoire", code: 'CI' },
  { name: 'Croatie', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Chypre', code: 'CY' },
  { name: 'République tchèque', code: 'CZ' },
  { name: 'République démocratique du Congo', code: 'CD' },
  { name: 'Danemark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominique', code: 'DM' },
  { name: 'République dominicaine', code: 'DO' },
  { name: 'Équateur', code: 'EC' },
  { name: 'Égypte', code: 'EG' },
  { name: 'Salvador', code: 'SV' },
  { name: 'Guinée équatoriale', code: 'GQ' },
  { name: 'Érythrée', code: 'ER' },
  { name: 'Estonie', code: 'EE' },
  { name: 'Eswatini', code: 'SZ' },
  { name: 'Éthiopie', code: 'ET' },
  { name: 'Fidji', code: 'FJ' },
  { name: 'Finlande', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambie', code: 'GM' },
  { name: 'Géorgie', code: 'GE' },
  { name: 'Allemagne', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Grèce', code: 'GR' },
  { name: 'Grenade', code: 'GD' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guinée', code: 'GN' },
  { name: 'Guinée-Bissau', code: 'GW' },
  { name: 'Guyane', code: 'GY' },
  { name: 'Haïti', code: 'HT' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hongrie', code: 'HU' },
  { name: 'Islande', code: 'IS' },
  { name: 'Inde', code: 'IN' },
  { name: 'Indonésie', code: 'ID' },
  { name: 'Iran', code: 'IR' },
  { name: 'Irak', code: 'IQ' },
  { name: 'Irlande', code: 'IE' },
  { name: 'Italie', code: 'IT' },
  { name: 'Jamaïque', code: 'JM' },
  { name: 'Japon', code: 'JP' },
  { name: 'Jordanie', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: 'Corée du Nord', code: 'KP' },
  { name: 'Corée du Sud', code: 'KR' },
  { name: 'Kosovo', code: 'XK' },
  { name: 'Koweït', code: 'KW' },
  { name: 'Kirghizistan', code: 'KG' },
  { name: 'Laos', code: 'LA' },
  { name: 'Lettonie', code: 'LV' },
  { name: 'Liban', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libye', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lituanie', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaisie', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malte', code: 'MT' },
  { name: 'Îles Marshall', code: 'MH' },
  { name: 'Mauritanie', code: 'MR' },
  { name: 'Maurice', code: 'MU' },
  { name: 'Mexique', code: 'MX' },
  { name: 'Micronésie', code: 'FM' },
  { name: 'Moldavie', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolie', code: 'MN' },
  { name: 'Monténégro', code: 'ME' },
  { name: 'Maroc', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibie', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Népal', code: 'NP' },
  { name: 'Pays-Bas', code: 'NL' },
  { name: 'Nouvelle-Zélande', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Macédoine du Nord', code: 'MK' },
  { name: 'Norvège', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palaos', code: 'PW' },
  { name: 'Palestine', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papouasie-Nouvelle-Guinée', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Pérou', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pologne', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Roumanie', code: 'RO' },
  { name: 'Russie', code: 'RU' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Saint-Kitts-et-Nevis', code: 'KN' },
  { name: 'Sainte-Lucie', code: 'LC' },
  { name: 'Saint-Vincent-et-les Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'Saint-Marin', code: 'SM' },
  { name: 'Sao Tomé-et-Principe', code: 'ST' },
  { name: 'Arabie saoudite', code: 'SA' },
  { name: 'Sénégal', code: 'SN' },
  { name: 'Serbie', code: 'RS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapour', code: 'SG' },
  { name: 'Slovaquie', code: 'SK' },
  { name: 'Slovénie', code: 'SI' },
  { name: 'Îles Salomon', code: 'SB' },
  { name: 'Somalie', code: 'SO' },
  { name: 'Afrique du Sud', code: 'ZA' },
  { name: 'Soudan du Sud', code: 'SS' },
  { name: 'Espagne', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Soudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Suède', code: 'SE' },
  { name: 'Suisse', code: 'CH' },
  { name: 'Syrie', code: 'SY' },
  { name: 'Taïwan', code: 'TW' },
  { name: 'Tadjikistan', code: 'TJ' },
  { name: 'Tanzanie', code: 'TZ' },
  { name: 'Thaïlande', code: 'TH' },
  { name: 'Timor oriental', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinité-et-Tobago', code: 'TT' },
  { name: 'Tunisie', code: 'TN' },
  { name: 'Turquie', code: 'TR' },
  { name: 'Turkménistan', code: 'TM' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Ouganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'Émirats arabes unis', code: 'AE' },
  { name: 'Royaume-Uni', code: 'GB' },
  { name: 'États-Unis', code: 'US' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Ouzbékistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Cité du Vatican', code: 'VA' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viêt Nam', code: 'VN' },
  { name: 'Yémen', code: 'YE' },
  { name: 'Zambie', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
]

export default countries
