export const DATE_FORMAT = 'DD-MM-YYYY'
export const TIME_FORMAT = 'HH:mm:ss'
export const DATE_TIME_FORMAT = 'DD-MM-YYYY HH:mm:ss'
export const DATE_TIME_ZONE_FORMAT = 'yyyy-MM-ddTHH:mm:ssZ'
export const DATE_FORMAT_API = 'YYYY-MM-DD'
