name: Auto Comment Merge Conflicts

on:
  workflow_dispatch:
  # push:
  #   branches-ignore:
  #     - dev
  #     - master
  #     - production
  #     - '!dependabot/*'
  #     - '!dependabot/*/**'

permissions:
  pull-requests: write

jobs:
  auto-comment-merge-conflicts:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: codytseng/auto-comment-merge-conflicts@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-body: 'Merge conflict...'
          wait-ms: 3000
          max-retries: 5
          label-name: conflict
          ignore-authors: dependabot
