name: Lint

on:
  pull_request:
    branches:
      - dev
      - '!dependabot/*'
      - '!dependabot/*/**'

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Code Linting
        run: npm run lint
