name: Prettier

on:
  pull_request:
    branches:
      - dev
      - '!dependabot/*'
      - '!dependabot/*/**'

jobs:
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettier checker
        uses: actionsx/prettier@v3
        with:
          args: --check --loglevel=warn .
